#!/bin/sh
#
# ~/.bash/ssh:jeff
#
# NOTE(JEFF): This configuration must always be compatible with the SH shell
# in order for this and the invocation from tmux to remain cross-platform.
#

# IMPORTANT(JEFF): Allow existing regular files to be overwritten by
# redirection of shell output, i.e.: `>` operator.
set +o noclobber

SSH_ENV="$HOME/.ssh/ssh_agent"

# Store SSH agent env in a file so we may reference the same daemon upon
# shell jumping -- especially in combination with tmux.
#
# SEE ALSO
# 1. `~/.tmux.conf:SSH_AUTH_SOCK`
# 2. https://stackoverflow.com/a/18915067
start_agent() {
    echo "INFO: Initializing a new SSH agent..."
    echo
    /usr/bin/ssh-agent -s | sed 's/^echo/#echo/' > "${SSH_ENV}"

    if [ -e "${SSH_ENV}" ]; then
      chmod 600 "${SSH_ENV}"
      # shellcheck disable=SC1090
      . "${SSH_ENV}" > /dev/null
      echo "INFO: SSH agent environment has been setup."
      echo
    fi
}

# Source SSH settings, if applicable

if [ -f "${SSH_ENV}" ]; then
    # shellcheck disable=SC1090
    . "${SSH_ENV}" > /dev/null

    #ps ${SSH_AGENT_PID} doesn't work under cywgin
    # NOTE(JEFF): This syntax we tried does not seem to work for us.
    #ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {

    # NOTE(JEFF): Feature check; busybox and other embedded
    # platforms often do not support all the common flags.
    if ! ps -o pid= "${SSH_AGENT_PID}" &>/dev/null; then
      ps -o pid= "${SSH_AGENT_PID}" > /dev/null || {
          start_agent;
      }
    fi
else
  start_agent;
fi

