[Behavior]
AutoSelectionDelay=600
BookmarkOpenMethod=new_tab
ConfirmDelete=true
ConfirmTrash=false
CtrlRightClick=true
NoUsbTrash=false
QuickExec=false
RecentFilesNumber=15
SelectNewFiles=true
SingleClick=false
SingleWindowMode=true
UseTrash=true

[Desktop]
AllSticky=false
BgColor=#000000
DesktopCellMargins=@Size(3 1)
DesktopIconSize=48
DesktopShortcuts=@Invalid()
FgColor=#ffffff
Font="Noto Sans,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
HideItems=false
LastSlide=
OpenWithDefaultFileManager=false
PerScreenWallpaper=false
ShadowColor=#000000
ShowHidden=false
SlideShowInterval=0
SortColumn=name
SortFolderFirst=true
SortHiddenLast=false
SortOrder=ascending
TransformWallpaper=false
Wallpaper=
WallpaperDialogSize=@Size(700 500)
WallpaperDialogSplitterPos=200
WallpaperDirectory=
WallpaperMode=none
WallpaperRandomize=false
WorkAreaMargins=12, 12, 12, 12

[FolderView]
BackupAsHidden=false
BigIconSize=64
CustomColumnWidths=@Invalid()
FolderViewCellMargins=@Size(3 3)
HiddenColumns=@Invalid()
Mode=detailed
NoItemTooltip=false
ScrollPerPixel=true
ShadowHidden=true
ShowFilter=true
ShowFullNames=true
ShowHidden=false
SidePaneIconSize=32
SmallIconSize=32
SortCaseSensitive=false
SortColumn=name
SortFolderFirst=true
SortHiddenLast=false
SortOrder=ascending
ThumbnailIconSize=224

[Places]
HiddenPlaces=@Invalid()

[Search]
ContentPatterns=@Invalid()
MaxSearchHistory=10
NamePatterns=@Invalid()
searchContentCaseInsensitive=false
searchContentRegexp=true
searchNameCaseInsensitive=false
searchNameRegexp=true
searchRecursive=false
searchhHidden=false

[System]
Archiver=ark
FallbackIconThemeName=oxygen
OnlyUserTemplates=false
SIUnit=false
SuCommand=lxqt-sudo %s
TemplateRunApp=false
TemplateTypeOnce=false
Terminal=ghostty

[Thumbnail]
MaxExternalThumbnailFileSize=-1
MaxThumbnailFileSize=4096
ShowThumbnails=true
ThumbnailLocalFilesOnly=false

[Volume]
AutoRun=true
CloseOnUnmount=true
MountOnStartup=false
MountRemovable=false

[Window]
AlwaysShowTabs=true
FixedHeight=480
FixedWidth=640
LastWindowHeight=947
LastWindowMaximized=false
LastWindowWidth=630
PathBarButtons=false
RememberWindowSize=true
ReopenLastTabs=true
ShowMenuBar=true
ShowTabClose=false
SidePaneMode=places
SidePaneVisible=false
SplitView=false
SplitViewTabsNum=0
SplitterPos=150
SwitchToNewTab=false
TabPaths=/home/jeff/Downloads, /home/jeff/Applications, /home/jeff/.config/conky, /home/jeff/.config/autostart
