# MPD Outputs
#
# SEE ALSO
# 1. https://mpd.readthedocs.io/en/latest/plugins.html#

# Audio Output ################################################################

# NOTE(jeff): This audio output seems to best handle switching system audio
# outputs on OS X, i.e.: Bluetooth headphones, without requiring a restart of
# mpd.
#audio_output {
  #type            "openal"
  #name            "OpenAL Audio Output"
  # encoder         "vorbis"
  #enabled         "no"
#}

# High fidelity HTTP streaming audio at 320kbps++ (FLAC)
#
# http://scorpio.local:6601
audio_output {
  type              "httpd"
  name              "Carp's Hi-Fi MPD stream"
  encoder           "flac"
  # !! HTTP streams on the web may not support multi-format tracks; it is
  # suggested that we used a fixed format, but...
  #format            "44100:16:2"
  bind_to_address   "0.0.0.0"
  port              "6601"
  max_clients       "4"
  enabled           "yes"
  # QoS: broadcast video
  dscp_class        "CS3"
  # FIXME(JEFF): This is unavailable as of the time that I have added this
  # metadata field. Let us pray that I get to it sooner than later!
  website           "https://music.fs1.home"
}

# Moderate fidelity HTTP streaming audio at 256kbps
#
# http://scorpio.local:6602
audio_output {
  type              "httpd"
  name              "Carp's med-fi MPD stream"
  encoder           "lame"
  bitrate           "256"
  # !! HTTP streams on the web may not support multi-format tracks; it is
  # suggested that we used a fixed format, but...
  #format            "44100:16:2"
  bind_to_address   "0.0.0.0"
  port              "6602"
  max_clients       "8"
  enabled           "yes"
  # QoS: broadcast video
  dscp_class        "CS3"
  website           "https://music.fs1.home"
}

# Low fidelity HTTP streaming audio at 128kbps
#
# http://scorpio.local:6603
audio_output {
  type              "httpd"
  name              "Carp's lo-fi MPD stream"
  encoder           "lame"
  bitrate           "128"
  # !! HTTP streams on the web may not support multi-format tracks; it is
  # suggested that we used a fixed format, but...
  # format            "44100:16:2"
  bind_to_address   "0.0.0.0"
  port              "6603"
  max_clients       "16"
  enabled           "no"
  # QoS: broadcast video
  dscp_class        "CS3"
  website           "https://music.fs1.home"
}

# NOTE(jeff): This audio output should **always** be enabled. The idea behind
# this is to always be feeding the current output with data when in use. This
# helps maintain the *exclusive* use of said output as seen by the desktop OS.
#
# First In First Out raw pcm data for use with ncmpcpp's audio visualizer
audio_output {
  type              "fifo"
  name              "FIFO Output"
  path              "~/.config/mpd/fifo"
  enabled           "yes"
}

# Decoding test output
# decoder {
#   plugin          "vorbis"
#   enabled         "yes"
# }

audio_output {
  type        "pulse"
  name        "PulseAudio"
  mixer_type  "hardware"
  enabled     "yes"
}

audio_output {
  type            "alsa"
  name            "ALSA"
  device          "hw:3"
  mixer_type      "hardware"
  mixer_device    "hw:1"
  mixer_control   "PCM" # PCM || Master
  mixer_index     "0"
  enabled         "no"
}

# JACK output
# audio_output {
#   type        "jack"
#   #device     "hw:0,0"
#   name        "JACK Output"
#   enabled     "no"
# }

# audio_output {
#   type            "alsa"
#   name            "ALSA"
#   device          "hw:1,0"
#   mixer_type      "hardware" # software || hardware
#   mixer_device    "hw:1"
#   mixer_control   "PCM" # PCM || Master
#   mixer_index     "0"
#   enabled         "no"
# }

audio_output {
  type            "null"
  name            "nill output"
  enabled         "yes"
}

audio_output {
  type            "pipe"
  name            "mpv playback engine"
  command         "mpv 2>/dev/null"
  enabled         "no"
}
