#!/bin/sh
#
# 2011-09/09:jeffrey.carp@gmail.com
#
#		~/.bash_login
#

case "$(uname -s)" in
	Darwin)
	;;
	Linux)
		# restore ALSA sfx levels
		alsactl -f "$HOME/.asound.state restore 0"
		alsactl -f "$HOME/.asound.state restore 1"
	;;
	*)
	;;
esac
