#!/bin/sh
#
# 2012-01/16:jeff
#
# 		~/.bash_cflags
#
# 	Local system compiler / linker flags for the GNU toolchain;
# relatively no tuning for the time being until I (re)-build a
# new system ...
#
# See also,
#
#	makepkg.conf(5)		makepkg(8)		pacman(8)		PKGBUILD(5)
#

#PROJECTS="$HOME/Projects"
#GIT_PROJ_ROOT="$HOME/git"

#FIXME/TODO: eval /etc/makepkg.conf
#export CARCH=""
#export CHOST=""
#export LDFLAGS="-W1,-O1,--sort-common,--as-needed,-z,relro,--hash-style=gnu"

#export CFLAGS="-march=i686 -mtune=generic -O2 -pipe -fstack-protector -D_FORTIFY_SOURCE=2"
#export CXXFLAGS=$CFLAGS
export MAKEFLAGS="-j3"
export LOCAL="libra"
#export PREFIX="/usr/local"

#export GEM_HOME="$HOME/.gem/ruby/1.9.3-p0"
#export GEM_PATH="/usr/lib/ruby/gems/1.9.3"
export RUBYOPT="-w"
#export RUBYLIB="/home/jeff/Projects/ruby/lib"
