#!/bin/bash
#
# 2016-02/21:jeff
#
# User function helpers

# Colored man pages for the win!
# Source: https://wiki.archlinux.org/index.php/Man_Page#Colored_man_pages
if [[ "$(which less)" ]]; then
  man()
  {
    env \
    LESS_TERMCAP_mb="$(printf "\e[1;31m")" \
    LESS_TERMCAP_md="$(printf "\e[1;31m")" \
    LESS_TERMCAP_me="$(printf "\e[0m")" \
    LESS_TERMCAP_se="$(printf "\e[0m")" \
    LESS_TERMCAP_so="$(printf "\e[1;44;33m")" \
    LESS_TERMCAP_ue="$(printf "\e[0m")" \
    LESS_TERMCAP_us="$(printf "\e[1;32m")" \
    man "$@"
  }
fi

if [[ -x "$(which ssh)" ]]; then
  function ssh()
  {
    if [[ "$1" = "-X" && -n "$2" ]]; then
      echo -ne "TRANSLATING /usr/bin/ssh argument one [-X] to [-Y], appended $2"
      command ssh "-Y" "$2"
    else
      command ssh "$@"
    fi
  }
fi

function osver()
{
  if [[ -x "$(which otool)" && -x "$(which grep)" ]]; then
    if [[ "$1" ]]; then
      otool_bin="$(which otool)" # bin path
      grep_bin="$(which grep)" # bin path

      # Should include the output of both version & sdk
      $otool_bin -l "$1" | $grep_bin -B 1 sdk
    else
      echo "Error: osver alias requires an input argument: specify a binary file to process."
    fi
  fi
}

if [[ -x "$(which grep)" ]]; then
  function fstring()
  {
    if [[ ! "$2" ]]; then
      grep "$1" -s -I -i -R --exclude-dir \*.git . "$@"
    else
      grep "$1" -s -I -i -R --exclude-dir \*.git "$@"
    fi
  }
fi

PLATFORM_CONFIG="${HOME}/.bash/functions.d/${NOM_PLATFORM}.sh"
if [[ -r "${PLATFORM_CONFIG}" ]]; then
  # shellcheck disable=SC1090
  source "${PLATFORM_CONFIG}"
fi
