#!/usr/bin/env bash
#
# Utility functions for supporting our BASH dotfiles
#
#

# Append "$1" to $PATH when non-existing
#
# 1. append_path snippet originates from Manjaro KDE's function call in
# `/etc/profile` as of circa 2024.
append_path() {
  case ":$PATH:" in
    *:"$1":*)
      # NOTE(JEFF): The path (pre)-exists; do nothing...
      true
    ;;
    *)
      PATH="${PATH:+$PATH:}$1"
    ;;
  esac

  #export PATH
}

# Check for the existence of a path that is executable.
#
# exists_exe(path = required)
#
# ...where path is a string containing the command for which
# we seek the existence of
exists_exe() {
  pathstr="$1"
  if [ -z "$pathstr" ]; then
    return 2
  fi

  if which "$pathstr" &>/dev/null; then
    return 0 # truthy
  else
    return 1 # err
  fi
}

# NOTE(JEFF): The remainder of .aliases is split up
# between our ~/.bash_profile, ~/.bashrc and ~/.bash_aliases

# .aliases by Skittles9823 2018 - 2019
#           Terminal Mods
#
# Functions which I'm gonna count as aliases
getperms() {
  rootcheck && $ROOT pm get-privapp-permissions $1 | sed "s/, /\n/g" 
}

getdenyperms() {
  rootcheck && $ROOT pm get-privapp-deny-permissions $1 | sed "s/, /\n/g" 
}

# https://stackoverflow.com/questions/394230/how-to-detect-the-os-from-a-bash-script/68706298#68706298
#if "$(uname -a | tr '[:upper:]' '[:lower:]' | grep -i -e 'Android'>/dev/null)"; then
#if [ -z "$OSTYPE" ]; then
  #if ! "$(uname -a|grep -i -e 'Android' >/dev/null)"; then
    #OSTYPE="linux-android"
  #fi
#fi

# See also: choose_terminal function
DEFAULT_TERMINALS_CONFIG=(
  "$(which ghostty &>/dev/null)"
  "$(which wezterm &>/dev/null)"
  "$(which xfce4-terminal &>/dev/null)"
  "$(which urxvtcd &>/dev/null)"
)

# Select the default terminal application to utilize; this function sets the TERMINAL variable to the path of the
# terminal that is chosen. The first one on the list to exist always wins! The TERMINAL env is used by various 
# utilities, such as the rofi-sensible-terminal script that inspired the creation of this function.
#
#[string] choose_terminal(terms = [optional, string])
#
# ...where `terms` is an optional, non-empty string of your terminal's name; if this `name` does not exist in the 
# system PATH, the call will fail and the terminal will never be considered. It is because of this that it is suggested
# that you always give the function the absolute path to the terminal you wish to add.
#
# TODO(JEFF): Profile this function -- hell, all of our shell init scripts -- and see how slow looping through an 
# array like this is. I am somewhat concerned about embedded systems, such as routers and such!
choose_terminal() {
  terminals=()  
  result=""

  term="$1"
  [ "$term" != "" ] && terminals+=("${term}")

  terminals+=("${DEFAULT_TERMINALS_CONFIG[@]}")

  for app in "${terminals[@]}"; do
    if [ -x "$app" ]; then
      result="$app"
      break;
    fi
  done

  echo "$result"
}

# TODO(JEFF): Finish impl
# `git lfs ls-files --json | jq .files[0].size`
bytes() {
  value="$1"
  result=$value
  return "$result"
}

kilobytes() {
  value=$(bytes "$1")
  result=$(("$value" * 1024))
  return "$result"
}

megabytes() {
  value=$(kilobytes "$1")
  result=$(("$value" * 1024))
  return "$result"
}

gigabytes() {
  value=$(megabytes "$1")
  result=$(("$value" * 1024))
  return "$result"
}

