#!/bin/sh
#
# 2012-10/12:jeff
#
#       ~/.bash_syscheck
#
# Helper script that does some rudimentary sanity checks for us
#

if [ ! -x "${HOME}/.bash/functions" ]; then
    echo "ERR: Ensure that ${HOME}/.bash/functions file permissions are executable (x) and readable (r)."
fi

if [ ! -x "${HOME}/.bash/prompt" ]; then
    echo "ERR: Ensure that ${HOME}/.bash/prompt file permissions are executable (x) and readable (r)."
fi

if [ ! -x "${HOME}/.bash/aliases" ]; then
    echo "ERR: Ensure that ${HOME}/.bash/aliases file permissions are executable (x) and readable (r)."
fi

# Misc. one-time setup configuration options
#
case "$(uname -s)" in
    Darwin)
        # http://fuse4x.org/options.html
        # http://fuse4x.org/faq.html
        if [ ! "$(sysctl vfs.generic.fuse4x.tunables.admin_group)" \
            == "vfs.generic.fuse4x.tunables.admin_group: 80" ]; then
            # TODO/FIXME: this ought to be a separate configuration opt check
            echo "Be sure to install the fuse4x port via Homebrew:\n"
            echo "brew install fuse4x"

            echo "To setup, execute this command after installing the fuse4x port via Homebrew:\n"
            echo "sudo sysctl -w vfs.generic.fuse4x.tunables.admin_group=80"

            echo "Also, add yourself to the admin group:\n"
            echo "dseditgroup -o edit -a $(whoami) -t user admin\n"
        fi
    ;;
    Linux)
    ;;
    *)
    ;;
esac
