#!/bin/sh

if [ $(id -u) -ne 0 ]; then
  echo "This script must be run as root";
  exit 1;
fi

echo "System-wide proxy is shutting down..."

gsettings set org.gnome.system.proxy mode 'none' ;

ENVPATH=$(grep PATH /etc/environment)
echo $ENVPATH > /tmp/penv
cat /tmp/penv > /etc/environment

printf "" > /etc/apt/apt.conf.d/95proxies

unset http_proxy https_proxy ftp_proxy no_proxy
unset HTTP_PROXY HTTPS_PROXY FTP_PROXY NO_PROXY

rm -rf /tmp/penv;
