#
#
# TODO(JEFF): setup docker secrets to store our PBS_PASSWORD
---

#version: "3.7"


#secrets:
  #pbs_passphrase:

networks:
  traefik-proxy:
    driver: overlay
    attachable: true
    external: true
    #external: false

volumes:
  config:
    driver: local

services:
  pbs:
    restart: unless-stopped
    image: "fdrake/proxmox-backup-client:latest"
    container_name: "pbs-1"
    command: "/config/pbc.sh" # proxmox-backup-client sub-command to run
    tmpfs:
      - /tmp:rw # Error 95 Operation Denied
    environment:
      - TZ=America/Chicago
      - LC_TIME=C.UTF-8
      - BACKUP_TARGETS=virgo_root.pxar:/mnt/srv virgo_home.pxar:/mnt/home
      - "NAMESPACE=virgo"
      - "PBS_REPOSITORY=jeff@pbs@pbs1-san.home:BackupDisk_npool0"
      #- PBS_FINGERPRINT=<fingerprint>
      #- PBS_REPOSITORY=root@pam!token@pbs:datastore
      - "NAMESPACE=scorpio"
    volumes:
      - config:/root/.config/proxmox-backup
      - ./mounts/config:/config:ro
    env_file:
      - .env
