"--------------------------------------------------------------
" file:         ~/.vimrc
" author:       fielding johnston - http://www.justfielding.com
"               jeff (additions)
"--------------------------------------------------------------

" NOTE(JEFF): The host-based branching here should only be used
" as a last resort!
function GetHostname()
  let hostStr = substitute(system('hostname'), '\n', '', '')
  return hostStr
endfunction

"let host = GetHostname()

" Detect the operating environment
"
" [string] OS_stamp(void)
"
" Returns one of the following strings:
" 'wsl', 'msys', 'linux', or 'windows'.
function OS_stamp()
  let envStr = toupper(substitute(system('uname -s'), '\n', '', ''))

  " ... Windows land
  if matchstr(envStr, 'WINDOWS') == 'WINDOWS' | return 'windows' | endif

  if matchstr(envStr, 'WSL') == 'WSL' | return 'wsl' | endif

  if matchstr(envStr, 'CYGWIN') == 'CYGWIN' | return 'cygwin' | endif

  " ... to do MinGW-specific stuff (Git Bash, mainly).
  if matchstr(envStr, 'MINGW') == 'MINGW' | return 'msys' | endif

  " ...base M$ stamp strings
  if has('win64') || has('win32') || has('win16')
    return 'windows'
  endif

  " ... MacOS
  if matchstr(envStr, 'DARWIN') == 'DARWIN' | return 'darwin' | endif

  " ... *nix types handling
  if matchstr(envStr, 'LINUX') == 'LINUX' | return 'linux' | endif

  if has('unix')
    return 'unix'
  endif

  " let l:uname = system('uname -srm')
  " if matchstr(l:uname, "WSL") == "WSL" | return 'wsl' | endif
  " if matchstr(l:uname, "MINGW") == "MINGW" | return 'msys' | endif
endfunction

" Detect the use of a "GUI" environment.
"
" [string] IsGUI(void)
"
" Returns one of the following strings:
" 'linux' or 'windows'
function IsGui()
  if has("X11") | return 'linux' | else | return 'windows' | endif
endfunction

" Set the default terminal for vim
if !exists('g:env')
  let g:env = OS_stamp()
  if g:env =~ 'linux'
    "set term=xterm-256color
  endif
endif

" FIXME(JEFF): Re-enable plugin management!
"call pathogen#infect() 			" vim plugins management

" IMPORTANT(JEFF): Fix warnings at startup regarding vim state
" FIXME(JEFF): 'unix' str
if g:env =~ 'linux' || g:env =~ 'darwin' || g:env =~ 'msys' || 
    g:env =~ 'cygwin' || g:env =~ 'unix'
  :call system("mkdir -p ~/.vim/backup")
  :call system("mkdir -p ~/.vim/tmp")
endif

" where to put backup files
set backupdir=~/.vim/backup/

" where to put tmp files
set directory=~/.vim/tmp/

" where to find colors, plugins and so on
if g:env =~ 'windows'
  "if has("win32") || has ("win16")
  set runtimepath=~/.vim
  "endif
endif

syntax on
colorscheme vice
"colorscheme lightline-vice
filetype plugin on

set nocompatible                                                        " allows me to keep my sanity
set backspace=2                                                         " full backspacing compat
set history=50                                                          " keep 50 lines of command line history
set ruler                                                               " show the cursor position all the time
set showcmd                                                             " display incomplete commands
set incsearch                                                           " do incremental searching
set hlsearch                                                            " highlight last used search pattern
set t_Co=256                                                            " use 256 colors
set encoding=utf-8                                                      " sets encoding to utf-8 for new files
set nowrap                                                              " don't wrap line
set textwidth=0                                                         " stops linewrapping at invisible margins
set lbr                                                                 " wrap text
set number                                                              " show line numbers
set backup                                                              " turn on auto backups
"set pastetoggle=<f5>                                                    " toggle paste mode
set clipboard+=unnamed                                                  " yank and copy to xclipboard
set wildmenu                                                            " enhanced tab-completion
set suffixesadd=.rb                                                     " comma seperated list of file suffixes
set includeexpr+=substitute(v:fname,'s$','','g')                        " expression substitution

" status bar info and appearance
set statusline=\ \%f%m%r%h%w\ ::\ %y\ [%{&ff}]\%=\ [%p%%:\ %l/%L]\ col:\ %c]  " content for statusline
set laststatus=2                                                        " lastwindow always has status line
set cmdheight=1                                                         " set 1 line limit for 'messages'
set noshowmode                                                          " Hide the default mode text

" indenting
set autoindent                                                          " turns autoidenting on for new lines
set smartindent                                                         " does the right thing (mostly)
set cindent                                                             " stricter rules for C programs
set shiftwidth=2                                                        " 2 cols for autoindenting

" tabs
set expandtab                                                           " use spaces instead of true tabs
set tabstop=2                                                           " 2 column tabs

let g:html_indent_tags = 'li\|p'                                        "

" maps!
" Q does formatting qith gq. Vim 5.0 style
map Q gq

" Shift or not to shift! that is the question
map ; :

" Force writing to a file with sudo
cmap w!! w !sudo tee % >/dev/null

" enables CTRL-U after inserting a line break
inoremap <C-U> <C-G>u<C-U>
" spacebar unhighlights search text
:noremap <silent> <Space> :silent noh<Bar>echo<CR>

" In many terminal emulators the mouse works just fine, thus enable it.
" NOTE(JEFF): If this needs additional branching, see `IsGui` function.
if has('mouse')
  set mouse=a
endif

" Only do this part when compiled with support for autocommands.
if has("autocmd")

  " Enable file type detection.
  " Use the default filetype settings, so that mail gets 'tw' set to 72,
  " 'cindent' is on in C files, etc.
  " Also load indent files, to automatically do language-dependent indenting.
  filetype plugin indent on
  set ofu=syntaxcomplete#Complete
  set path+=/path/to/your/rails-application/app/**
  set path+=/path/to/your/rails-application/lib/**
  set suffixesadd=.rb
  set includeexpr+=substitute(v:fname,'s$','','g')

  " Put these in an autocmd group, so that we can delete them easily.
  augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78

  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid or when inside an event handler
  " (happens when dropping a file on gvim).
  " Also don't do it when the mark is in the first line, that is the default
  " position when opening a file.
  autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif

  augroup END

endif " has("autocmd")

" highlighting tabs, trailing white space and non breaking spaces
if &term !=# "linux"
    set list listchars=tab:\»\ ,trail:·,nbsp:-
endif

set noerrorbells novisualbell 	" [disabled] audible && visual queue bells
set t_vb=                     	" [disabled] visual bell

if g:env =~ 'windows'
  set term=win32
endif

" Enable italics support for comment syntax
" screen-256color-italic
if &term =~ 'italic'
  highlight Comment cterm=italic
endif

:nnoremap <leader>m :silent !open -a Marked.app '%'<cr>

" default location of ctags
set tags=.tags

" Mac OS X aliases the unnamed register to the + register AKA X11 clipboard
" SOURCE: http://vim.wikia.com/wiki/Accessing_the_system_clipboard
"set clipboard=unnamedplus

" Highlight column 80
if exists('+colorcolumn') "vim 7.3
  set colorcolumn=80
else
  au BufWinEnter * let w:m2=matchadd('ErrorMsg', '\%>80v.\+', -1)
endif

" NerdTree file tree style (list)
let g:netrw_liststyle=3

" Quick access to vim's file explorer (netrw)
" map <F5> :E
nmap <C-f> :E<CR>

" vim-gitgutter; default to line highlighting
let g:gitgutter_highlight_lines=1

" QBASIC syntax highlighting
au BufRead,BufNewFile *.bac* colorscheme bacon " BaCON
au BufRead,BufNewFile *.bas* colorscheme bacon " Gambas, etc.

" vim-tagbar plugin; Exuberant ctags (symbol browser)
nmap <C-T> : TagbarToggle<CR>

" vim-fuzzyfinder key bindings
" nmap <C-p> :FufTaggedFile<CR>

" vim-ctrlp key bindings

