"--------------------------------------------------------------
" file:         ~/.vimrc
" author:       fielding johnston - http://www.justfielding.com
"               jeff (additions)
"--------------------------------------------------------------

" TODO(JEFF): Install the following plugins once we have plugins re-enabled
" for vim!
"
" 1. [Use the same clipboard across vim & tmux](https://github.com/roxma/vim-tmux-clipboard.git)
" 2. [Copy text over SSH](https://github.com/haya14busa/vim-poweryank)

" NOTE(JEFF): The host-based branching here should only be used
" as a last resort!
function GetHostname()
  let hostStr = substitute(system('hostname'), '\n', '', '')
  return hostStr
endfunction

"let host = GetHostname()

" Detect the operating environment
"
" [string] OS_stamp(void)
"
" Returns one of the following strings:
" 'wsl', 'msys', 'linux', or 'windows'.
function OS_stamp()
  let envStr = toupper(substitute(system('uname -s'), '\n', '', ''))

  " ... Windows land
  if matchstr(envStr, 'WINDOWS') == 'WINDOWS' | return 'windows' | endif

  if matchstr(envStr, 'WSL') == 'WSL' | return 'wsl' | endif

  if matchstr(envStr, 'CYGWIN') == 'CYGWIN' | return 'cygwin' | endif

  " ... to do MinGW-specific stuff (Git Bash, mainly).
  if matchstr(envStr, 'MINGW') == 'MINGW' | return 'msys' | endif

  " ...base M$ stamp strings
  if has('win64') || has('win32') || has('win16')
    return 'windows'
  endif

  " ... MacOS
  if matchstr(envStr, 'DARWIN') == 'DARWIN' | return 'darwin' | endif

  " ... *nix types handling
  if matchstr(envStr, 'LINUX') == 'LINUX' | return 'linux' | endif

  if has('unix')
    return 'unix'
  endif

  " let l:uname = system('uname -srm')
  " if matchstr(l:uname, "WSL") == "WSL" | return 'wsl' | endif
  " if matchstr(l:uname, "MINGW") == "MINGW" | return 'msys' | endif
endfunction

" TODO(JEFF): Figure out how we can best determine when we are on Android OS
" using Termux (or probably any other) as the shell. The function returns
" 'linux' for us. Perhaps we could do an additional check [1]..? The other
" idea that immediately comes to mind is seeking out a file path that is
" unique to Android OS?
"
" 1. uname -o
" 2. uname -s
function MachineStamp()
  " TODO(JEFF): Verify that `uname -s` produces the same output under Termux
  " on Android OS. Darwin (MacOS) does not support the `-o` switch.
  let envStr = toupper(substitute(system('uname -s'), '\n', '', ''))

  " ... Android OS
  if matchstr(envStr, 'Android') == 'Android' | return 'android' | endif
  if matchstr(envStr, 'DARWIN') == 'DARWIN' | return 'darwin' | endif
  return envStr
endfunction

if !exists('g:stamp')
  let g:stamp = MachineStamp()
endif

" Detect the use of a "GUI" environment.
"
" [string] IsGUI(void)
"
" Returns one of the following strings:
" 'linux' or 'windows'
"
" FIXME(JEFF): Do not use this function until we deal with the other possible
" environments (MacOS, etc).
function IsGui()
  " TODO(JEFF): Does this check return TRUE when we are
  " inside Wayland env? This returns 'windows' under darwin (MacOS) -_-
  if has("X11") | return 'linux' | else | return 'windows' | endif
endfunction

if !exists('g:env')
  let g:env = OS_stamp()
endif

" DEPRECATED(JEFF): We should never set the term variable directly
" unless we are debugging something! Instead, it should only be
" used as a R/O env as a "feature" test. This will be removed
" entirely upon additional tests under our three major workstation
" environments.
"
" Set the default terminal for vim
"if g:env =~ 'linux'
  "set term=xterm-256color
"endif

" FIXME(JEFF): Re-enable plugin management?
"call pathogen#infect() 			" vim plugins management

" IMPORTANT(JEFF): Ensure that we have our vim env setup properly so that
" we do not see any warnings upon start or especially on file save!
"
" 1. https://wiki.archlinux.org/title/Vim#Workaround_for_XDG_Base_Directory_specification

" where to put backup files
set backupdir=$HOME/.vim/backup/ | call mkdir(&backupdir, 'p')

" where to put tmp (swap) files
"
" 1. https://wiki.archlinux.org/title/Vim#Workaround_for_XDG_Base_Directory_specification
"set directory=$HOME/.vim/tmp/ | call mkdir(&directory, 'p')
set directory=$HOME/.vim/swap/ | call mkdir(&directory, 'p')

set undodir=$HOME/.vim/undo | call mkdir(&undodir, 'p')
set viewdir=$HOME/.vim/view | call mkdir(&viewdir, 'p')

if !has('nvim') | set viminfofile=$HOME/.vim/viminfo | endif

" where to find colors, plugins and so on
if g:env =~ 'windows'
  set runtimepath=~/.vim
elseif g:stamp =~ 'android'
  " NOTE(JEFF): I believe that the only time this is necessary would be when
  " we are using Termux shell on Android OS, due to the unusual need for us
  " to use two different HOME paths (THOME and SDHOME).
  set runtimepath+=$HOME/.vim
else
  " NOTE(JEFF): We need not bother setting anything here, least in the typical
  " case. It is common for distributions to statically include $HOME/.vim in
  " the distribution's build of vim.
endif

syntax on
colorscheme vice
"colorscheme lightline-vice
filetype plugin on

" NOTE(JEFF): Improve handling of file modifications while outside of
" of vim, such as when we are resolving merge conflicts; this
" enablement will prevent Error 813 by automatically reading the file
" from disk if it was changed.
set autoread
set nocompatible                                                        " allows me to keep my sanity
set backspace=2                                                         " full backspacing compat
set history=50                                                          " keep 50 lines of command line history
set ruler                                                               " show the cursor position all the time
set showcmd                                                             " display incomplete commands
set incsearch                                                           " do incremental searching
set hlsearch                                                            " highlight last used search pattern
set t_Co=256                                                            " use 256 colors
set encoding=utf-8                                                      " sets encoding to utf-8 for new files
set nowrap                                                              " don't wrap line
set textwidth=0                                                         " stops linewrapping at invisible margins
set lbr                                                                 " wrap text
set number                                                              " show line numbers
set backup                                                              " turn on auto backups
"set pastetoggle=<f5>                                                    " toggle paste mode
set clipboard+=unnamed                                                  " yank and copy to xclipboard
set wildmenu                                                            " enhanced tab-completion
set suffixesadd=.rb                                                     " comma seperated list of file suffixes
set includeexpr+=substitute(v:fname,'s$','','g')                        " expression substitution
" status bar info and appearance
set statusline=\ \%f%m%r%h%w\ ::\ %y\ [%{&ff}]\%=\ [%p%%:\ %l/%L]\ col:\ %c]  " content for statusline
set laststatus=2                                                        " lastwindow always has status line
set cmdheight=1                                                         " set 1 line limit for 'messages'
set noshowmode                                                          " Hide the default mode text

" indenting
set autoindent                                                          " turns autoidenting on for new lines
set smartindent                                                         " does the right thing (mostly)
set cindent                                                             " stricter rules for C programs
set shiftwidth=2                                                        " 2 cols for autoindenting

" tabs
set expandtab                                                           " use spaces instead of true tabs
set tabstop=2                                                           " 2 column tabs

let g:html_indent_tags = 'li\|p'                                        "

" maps!
" Q does formatting qith gq. Vim 5.0 style
map Q gq

" Shift or not to shift! that is the question
map ; :

" Force writing to a file with sudo
cmap w!! w !sudo tee % >/dev/null

" enables CTRL-U after inserting a line break
inoremap <C-U> <C-G>u<C-U>
" spacebar unhighlights search text
:noremap <silent> <Space> :silent noh<Bar>echo<CR>

" In many terminal emulators the mouse works just fine, thus enable it.
" NOTE(JEFF): If this needs additional branching, see `IsGui` function.
if has('mouse')
  set mouse=a
endif

" Only do this part when compiled with support for autocommands.
if has("autocmd")

  " Enable file type detection.
  " Use the default filetype settings, so that mail gets 'tw' set to 72,
  " 'cindent' is on in C files, etc.
  " Also load indent files, to automatically do language-dependent indenting.
  filetype plugin indent on
  set ofu=syntaxcomplete#Complete
  set path+=/path/to/your/rails-application/app/**
  set path+=/path/to/your/rails-application/lib/**
  set suffixesadd=.rb
  set includeexpr+=substitute(v:fname,'s$','','g')

  " Put these in an autocmd group, so that we can delete them easily.
  augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78

  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid or when inside an event handler
  " (happens when dropping a file on gvim).
  " Also don't do it when the mark is in the first line, that is the default
  " position when opening a file.
  autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif

  augroup END

endif " has("autocmd")

" highlighting tabs, trailing white space and non breaking spaces
if &term !=# "linux"
    set list listchars=tab:\»\ ,trail:·,nbsp:-
endif

set noerrorbells novisualbell 	" [disabled] audible && visual queue bells
set t_vb=                     	" [disabled] visual bell

if g:env =~ 'windows'
  set term=win32
endif

" Enable italics support for comment syntax
" screen-256color-italic
if &term =~ 'italic' | elseif &term =~ 'iTerm.app'
  highlight Comment cterm=italic
endif

:nnoremap <leader>m :silent !open -a Marked.app '%'<cr>

" default location of ctags
set tags=.tags

" Mac OS X aliases the unnamed register to the + register AKA X11 clipboard
" SOURCE: http://vim.wikia.com/wiki/Accessing_the_system_clipboard
"set clipboard=unnamedplus

" Highlight column 80
if exists('+colorcolumn') "vim 7.3
  set colorcolumn=80
else
  au BufWinEnter * let w:m2=matchadd('ErrorMsg', '\%>80v.\+', -1)
endif

" NerdTree file tree style (list)
let g:netrw_liststyle=3

" Quick access to vim's file explorer (netrw)
" map <F5> :E
nmap <C-f> :E<CR>

" vim-gitgutter; default to line highlighting
let g:gitgutter_highlight_lines=1

" QBASIC syntax highlighting
au BufRead,BufNewFile *.bac* colorscheme bacon " BaCON
au BufRead,BufNewFile *.bas* colorscheme bacon " Gambas, etc.

" vim-tagbar plugin; Exuberant ctags (symbol browser)
nmap <C-T> : TagbarToggle<CR>

" vim-fuzzyfinder key bindings
" nmap <C-p> :FufTaggedFile<CR>

" vim-ctrlp key bindings

