#!/bin/bash

command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting '.git/hooks/post-checkout'.\n"; exit 2; }
git lfs post-checkout "$@"

# NOTE(jeff): If we do not always stow our configuration file, we may forget
# to restow updated configuration options on our many different environments!
#
# This ought to prevent that from happening.
[[ -x "$(command -v stow)" ]] && stow stow

