#!/bin/bash
#
# Jeffrey Carpenter <jeffrey.carp@gmail.com>
#
#   Local development config for hobbyist software development & general system
# administration
#

# convenience bash shell vars for common user paths
export DESKTOP="$HOME/Desktop"
export DOCUMENTS="$HOME/Documents"
export DOWNLOADS="$HOME/Downloads"
export MOVIES="$HOME/Movies"
export MUSIC="$HOME/Music"
export PICTURES="$HOME/Pictures"
export PROJECTS="$HOME/Projects"
export TMP="$HOME/tmp"
export TORRENTS="$HOME/Downloads/torrents"

export NOM="$PROJECTS/nomlib.git"
export TT="$PROJECTS/ttcards.git"
export CFG="$PROJECTS/dotfiles"
export HCFG="$PROJECTS/homebrew"

# NOTE(jeff): This is the local host's installation prefix for user-land
# applications
LOCAL_SITE_PREFIX="/usr/local"

case "$(uname -s)" in
  Darwin)
    if [[ -x "$(which brew)" ]]; then
      LOCAL_SITE_PREFIX=$(brew --prefix)
    fi

    case "$(hostname)" in
      virgo.local) # MacBook Air Mid 2011 [Intel Core i5 1.6Ghz]

      # CC & CXX should not need to be set
      #export CC="/usr/bin/clang"
      # export CXX="/usr/bin/clang++"

      # Number of CPU threads to spawn for clang, GCC && CTest
      export NUM_THREADS=2
      export MAKEFLAGS="-j${NUM_THREADS}"
      export CTEST_PARALLEL_LEVEL=$((NUM_THREADS+2))

      # It is a personal preference to use /usr/bin/xcode-select to set the
      # default DEVELOPER_DIR path, instead of setting it from the shell
      # environment; i.e.: eases the use of concurrent build environments.
      #
      # See also: man 1 xcode-select
      #export DEVELOPER_DIR="/Applications/Xcode.app/Contents/Developer"

      #export CCACHE_PATH="/usr/local/opt/ccache/libexec"
      #CCACHE_DIR="/ramdisk/dir"; export CCACHE_DIR

      # Note that $CCACHE_PATH be included early on, so that it does not get
      # overridden by the standard search paths, i.e.: /usr/local/bin, /usr/bin,
      # etc.
      #export PATH="$CCACHE_PATH:$PATH"

      # node.js
      export NODE_PATH="/usr/local/lib/node_modules"

      # emscripten
      #EMMAKEN_COMPILER="/usr/local/bin/clang++"; export EMMAKEN_COMPILER

      # Source: http://crossgcc.rts-software.org/doku.php?id=start
      # PATH="/usr/local/gcc-4.8.0-qt-4.8.4-for-mingw32/win32-gcc/bin:${PATH}"
      # PATH="${HOME}/local/opt/bin:${PATH}"; export PATH

      # Additional pkg-config paths
      export PKG_CONFIG_PATH="/opt/X11/lib/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/pkgconfig:/usr/local/Cellar/curl/7.42.1/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10"

      # qt52-dev
      export PKG_CONFIG_PATH="/usr/local/opt/qt52/lib/pkgconfig:${PKG_CONFIG_PATH}"

      export PYTHONPATH=${LOCAL_SITE_PREFIX}/lib/python2.7/site-packages:${PYTHONPATH}

      #export GL_ENABLE_DEBUG_ATTACH=YES
    ;; # end case virgo.local
    esac

    case "$(hostname)" in
      "scorpio.local")

    # export GL_ENABLE_DEBUG_ATTACH=YES

    # Number of CPU threads to spawn for clang, GCC && CTest

    export NUM_THREADS=6    # CPU is an eight-core 64-bit Intel Haswell
    export MAKEFLAGS="-j${NUM_THREADS}"
    export CTEST_PARALLEL_LEVEL=$((NUM_THREADS+2))

    # node.js
    export NODE_PATH="/usr/local/lib/node_modules"

    # Additional pkg-config paths
    export PKG_CONFIG_PATH="/opt/X11/lib/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/pkgconfig:/usr/local/Cellar/curl/7.42.1/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10"

    # qt52-dev
    export PKG_CONFIG_PATH="/usr/local/opt/qt52/lib/pkgconfig:${PKG_CONFIG_PATH}"

    # Add LLVM clang module for static analysis of code to system PATH
    STATIC_CPP_ANALYZER=/usr/local/opt/llvm/share/clang/tools/scan-build
    if [[ -x $STATIC_CPP_ANALYZER ]]; then
      PATH="$STATIC_CPP_ANALYZER:$PATH"; export PATH
    fi

    ;; # end case scorpio.local
    esac # end switch hostname
    ;; # end case Darwin

  Linux)
    case "$(hostname)" in
      libra.local)

      # Number of CPU threads to spawn for clang, GCC && CTest
      export NUM_THREADS=1
      export MAKEFLAGS="-j${NUM_THREADS}"
      export CTEST_PARALLEL_LEVEL=${NUM_THREADS}
    ;; # end case libra.local
    esac # end switch hostname
    # [generic Linux cfg]
  ;; # end case Linux
  *)
  ;;
esac

# NOTE(jeff): Setup our local Ruby environment using rbenv
NOM_USE_RBENV=true
RUBY_RC="${HOME}/.bash/ruby_config.sh"
if [[ -x "$RUBY_RC" ]]; then
  source "${RUBY_RC}"
fi

# Show GTest diagnostics output
export CTEST_OUTPUT_ON_FAILURE=true

# Colored logging output from nomlib
export NOM_COLOR=always
