#!/bin/sh
#
# 2011-07-20:jeff
#
# 		~/.bashlib
#
#   Local bash (1) functions executed for non-login interactive shells.
#


if [ "$(which less)" ]; then
  # Source: https://wiki.archlinux.org/index.php/Man_Page#Colored_man_pages
  man()
  {
    env \
    LESS_TERMCAP_mb=$(printf "\e[1;31m") \
    LESS_TERMCAP_md=$(printf "\e[1;31m") \
    LESS_TERMCAP_me=$(printf "\e[0m") \
    LESS_TERMCAP_se=$(printf "\e[0m") \
    LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
    LESS_TERMCAP_ue=$(printf "\e[0m") \
    LESS_TERMCAP_us=$(printf "\e[1;32m") \
    man "$@"
  }
fi

case "$(uname -s)" in
  Darwin)
    # Derives from Fielding's dotfiles repo
    # https://github.com/justfielding/dotfiles
    timecap ()
    {
      pwd_bin="$(which pwd)"
      parent="$(pwd_bin)"
      filenumber=${1:-1}
      delay=${2:-5}
      scdir=${3:-$(parent)}
      date_bin=$(which date)
      screencap_bin="$(which screencapture)"
      i=$filenumber

      while [ 1 ]
        do $screencap_bin -t jpg -x ${scdir}${i}_${timestamp}.jpg
        timestamp="$($date_bin +%y-%m-%d_%s)"
        echo "Capturing to ${i}_${timestamp}.jpg"
        let i++
        sleep $delay
      done
    }
  ;;
  Linux)
    function apkg()
    {
      if [[ -z "$1" ]]; then
        echo "Usage: apkg <pkg> ... where <pkg> is the AUR package name"
      else
        command wget http://aur.archlinux.org/packages/$1/$1.tar.gz
      fi
    }

    if [ -x "$(which geany)" ]; then
      function geany()
      {
        command geany "$@" &
      }
    fi

    if [ -x "$(which scite)" ]; then
      function scite()
      {
        if [[ "$#" -ge 1 ]]; then # test expression: >=
          command scite "$@" &
        else
          echo -e "Usage: scite.alias <file(s)>"
        fi
      }
    fi

    if [ -x "$(which firefox)" ]; then
      function firefox() {
          command firefox "$@" &
      }
    fi

    if [ -x "$(which meld)" ]; then
      function meld() {
          command meld "$@" &
      }
    fi

    if [ -x "$(which bless)" ]; then
      function bless() {
          command bless "$@" &
      }
    fi

    if [ -x "$(which gtkman)" ]; then
      function gtkman() {
          command gtkman "$1" &
      }
    fi

    if [ -x "$(which epdfview)" ]; then
      function pdf() {
          command epdfview "$1" &
      }
    fi

    if [ -x "$(which ggv)" ]; then
      function ggv() {
          command ggv "$1" &
      }
    fi

    if [ -x "$(which pkgbrowser)" ]; then
      function pkgbrowser() {
          command pkgbrowser "$1" &
      }
    fi

    if [ -x "$(which luakit)" ]; then
      function luakit() {
          command luakit "$@" &
      }
    fi

    if [ -x "$(which thunar)" ]; then
      function thunar()
      {
        if [ -n "$1" ]; then
          command thunar "$@" &
        else
          command thunar . &
        fi
      }
    fi

    if [ -x "$(which gitg)" ]; then
      function gitg()
      {
        if [ -n "$1" ]; then
          command gitg "$@" &
        else
          command gitg . &
        fi
      }
    fi

    if [ -x "$(which alsamixer)" ]; then
      function alsamixer()
      {
        if [ -n "$1" ]; then
          command alsamixer "$@"
        else
          command alsamixer -c0
        fi
      }
    fi
    ;;
    *)
    ;;
  esac

if [ -x "$(which ssh)" ]; then
  function ssh()
  {
    if [[ "$1" = "-X" && -n "$2" ]]; then
      echo -ne "TRANSLATING /usr/bin/ssh argument one [-X] to [-Y], appended $2"
      command ssh "-Y" "$2"
    else
      command ssh "$@"
    fi
  }
fi

if [[ -x "$(which sha1sum)" && -x "$(which openssl)" ]]; then
  function sha1calc()
  {
    if [[ $@ ]]; then
      openssl="$(which openssl)" # bin path
      eval echo -n \""$@\"" | $openssl sha1
    else
      echo "Err: sha1calc requires textual input arguments."
    fi
  }
else
  echo "Err: internal function 'sha1calc' is disabled -- necessary commands not found"
fi

if [[ -x "$(which md5)" && -x "$(which openssl)" ]]; then
  function md5calc()
  {
    if [[ $@ ]]; then
      openssl="$(which openssl)" # bin path
      eval echo -n \""$@\"" | $openssl md5
    else
      echo "Err: md5calc requires textual input arguments."
    fi
  }
else
  echo "WARNING: internal function 'md5calc' is disabled -- necessary commands not found"
fi

if [[ -x "$(which otool)" && -x "$(which grep)" ]]; then
  function osver()
  {
    if [[ "$1" ]]; then
      otool_bin="$(which otool)" # bin path
      grep_bin="$(which grep)" # bin path

      # Should include the output of both version & sdk
      $otool_bin -l "$1" | $grep_bin -B 1 sdk
    else
      echo "Error: osver alias requires an input argument: specify a binary file to process."
    fi
  }
else
  echo "WARNING: internal function 'osver' is disabled -- necessary commands not found."
fi

if [[ -x "$(which brew)" ]]; then
  function brewupgrade()
  {
    brew doctor; brew update; brew upgrade; brew missing
  }
else
  echo "Error: brew command not found -- brewupgrade alias is unavailable."
fi
