#!/bin/sh
#
# 2012-01/16:jeff
#
#     ~/.bash_cflags
#
#   Local system compiler / linker flags for the GNU toolchain;
# relatively no tuning for the time being until I (re)-build a
# new system ...
#
# See also,
#
# makepkg.conf(5)   makepkg(8)    pacman(8)   PKGBUILD(5)
#

#PROJECTS="$HOME/Projects"
#GIT_PROJ_ROOT="$HOME/git"

#FIXME/TODO: eval /etc/makepkg.conf
#export CARCH=""
#export CHOST=""
#export LDFLAGS="-W1,-O1,--sort-common,--as-needed,-z,relro,--hash-style=gnu"

#export CFLAGS="-march=i686 -mtune=generic -O2 -pipe -fstack-protector -D_FORTIFY_SOURCE=2"
#export CXXFLAGS=$CFLAGS

case "$(uname -s)" in
  Darwin)
    CC="/usr/bin/clang"; export CC
    CXX="/usr/bin/clang++"; export CXX
    MAKEFLAGS="-j4"; export MAKEFLAGS # MacBook Air Mid 2011
    DEVELOPER_DIR="/Users/$(whoami)/Applications/Developer/Xcode.app/Contents/Developer"; export DEVELOPER_DIR
    CCACHE_PATH="/usr/local/Cellar/ccache/3.1.9/libexec"; export CCACHE_PATH
    #CCACHE_DIR="/ramdisk/dir"; export CCACHE_DIR
    NODE_PATH="/usr/local/lib/node_modules"; export NODE_PATH
    #EMMAKEN_COMPILER="/usr/local/bin/clang++"; export EMMAKEN_COMPILER
    PATH="$PATH:/usr/local/gcc-4.8.0-qt-4.8.4-for-mingw32/win32-gcc/bin"; export PATH
  ;;
  Linux)
    MAKEFLAGS="-j4"; export MAKEFLAGS
  ;;
  *)
  ;;
esac

LOCAL="virgo"; export LOCAL

#if [ "$(which pkg-config)" ]; then
  #SDL_DEV="$(pkg-config --cflags --libs sdl SDL_image SDL_mixer SDL_ttf)"; export SDL_DEV
#fi

# removed PREFIX due to NPM trying to use this for global install dir
#
#export PREFIX="~/local"

if [ -f "$(which rbenv)" ]; then
  eval "$(rbenv init -)"
  PATH="$HOME/.rbenv/versions/1.9.3-p0/bin:$PATH"; export PATH
fi

#export GEM_HOME="$HOME/.gem/ruby/1.9.3-p0"
#export GEM_PATH="$HOME/.gem/ruby/1.9.3-p0"
#export GEM_PATH="/usr/lib/ruby/gems/1.9.3"
#export RUBYOPT="-w"
#RUBYLIB="/Library/Ruby"; export RUBYLIB
#export RUBYLIB="/home/jeff/Projects/ruby/lib"
