#!/bin/bash
#
# 2011-08-24: jeffrey.carp@gmail.com
#
#   ~/.bash_profile
#
# Local bash (1) profile executed for login shells.
#

#if [[ -z $DISPLAY && $(tty) = /dev/tty1 ]]; then

#if [[ -n $(tty) ]]; then
# command tmux
#fi

PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin";

case "$(uname -s)" in
  Darwin)
    PATH="${PATH}:${HOME}/Applications:/usr/X11/bin"

    # Un-hide my user's Library directory
    chflags nohidden ~/Library

    # Show Debug menu in App Store
    defaults write com.apple.appstore ShowDebugMenu -bool true

    # Show Debug menu in Disk Utility
    defaults write com.apple.DiskUtility DUDebugMenuEnabled 1

    # Enable AirDrop over Ethernet and on unsupported Macs running Lion
    defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

    # Avoid creating .DS_Store files on network volumes
    defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

    # Use current directory as default search scope in Finder
    defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

    # Disable Apptivate's menu icon:
    # defaults write se.cocoabeans.apptivate TAShowStatusbarIcon 0

    # Enable Contacts Debug menu
    defaults write com.apple.AddressBook ABShowDebugMenu -bool true

    # Enable DVDPlayer Debug menu
    defaults write com.apple.DVDPlayer EnableDebugging -bool true

    # Optional integration of our UNIX shell command history, current working
    # directory and more for iTerm 2.9.x
    #
    # See also: https://iterm2.com/shell_integration.html
    ITERM_SHELL_INTEGRATION_SH=${HOME}/.iterm2_shell_integration.bash
    if [[ -x "/Applications/iTerm.app/Contents/MacOS/iTerm" ||
          -x "${HOME}/Applications/iTerm.app/Contents/MacOS/iTerm" ]]; then
      source ${ITERM_SHELL_INTEGRATION_SH}
    fi

  ;;
  Linux)
    PATH="$PATH:$HOME/.config/feh/themes"
  ;;
  *)
  ;;
esac

export PATH

export XDG_DATA_HOME=${HOME}/.local/share
export XDG_CONFIG_HOME=${HOME}/.config

if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
fi

umask 022
