#!/bin/sh
#
# 2011-08-24: jeffrey.carp@gmail.com
#
#		~/.bash_profile
#
# Local bash (1) profile executed for login shells.
#

#if [[ -z $DISPLAY && $(tty) = /dev/tty1 ]]; then

#if [[ -n $(tty) ]]; then
#	command tmux
#fi

PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"

case "$(uname -s)" in
	Darwin)
		PATH="$PATH:$HOME/Applications:/usr/X11/bin"
	;;
	Linux)
		PATH="/snap/bin:${HOME}/.config/feh/themes:$PATH"
	;;
	*)
	;;
esac

if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
fi

umask 022

# rbenv path related variables
if [[ -x $(which rbenv) ]]; then
  eval "$(rbenv init -)"
fi

# golang env
GOPATH="${HOME}/local/src/golang"; export GOPATH

if [[ ! (-d "${GOPATH}") ]]; then
  mkdir -p "${GOPATH}/bin" || exit 255
fi

GOBIN="${GOPATH}/bin"; export GOBIN
PATH="$GOBIN:$PATH"

# mkcert
CAROOT="${HOME}/pki"; export CAROOT
