#!/bin/sh
# Jeffrey Carpenter <jefffrey.carp@gmail.com>
#

#"\e[1~"	beginning-of-line # ^A
#"\e[4~"	end-of-line # ^E

#"\e[1;5D"	backward-word
#"\e[1;5C"	forward-word

# http://www.ibb.net/~anne/keyboard.html
#"\e[3~": delete-char
# this is actually equivalent to "\C-?": delete-char

# Source: https://github.com/justfielding/dotfiles
set editing-mode vi
set blink-matching-paren on
set completion-ignore-case on
set expand-tilde off

# Use Unicode & do NOT use the "8bit hack" to input/output non-ASCII characters
# See http://code.google.com/p/iterm2/wiki/Keybindings
set input-meta on
set output-meta on
set convert-meta off

$if mode=vi

  set keymap vi-command
  # these are for vi-command mode
  "\e[A": history-search-backward
  "\e[B": history-search-forward

  # Insert the arguments from the last command
  "p": "i !!*\r"

  set keymap vi-insert
  # these are for vi-insert mode
  "\e[A": history-search-backward
  "\e[B": history-search-forward

  # Needed because binding 'p' in command mode above wipes its insert mode
  # function, too. This fixes that, and will insert 'p' when you type 'p'.
  "p": self-insert

  "\e[1~" beginning-of-line # ^A
  "\e[4~" end-of-line # ^E

  "\e[1;5D"   backward-word
  "\e[1;5C"   forward-word
$endif
