#!/bin/sh
#
# http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
#
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .tags.$$" EXIT
ctags --tag-relative -Rf.tags.$$ --exclude=.git --languages=-sql
#mv .tags.$$ .tags

